version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8001:8001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
      - /usr/src/app/node_modules
    ports:
      - "27017:27017"